import React from 'react';

const ViewBills = ({ bill ,payBill}) => {



  return (

    <div>
      <div className="container">
        <div className="card m-2" style={{ 'backgroundColor': '#f2f2f2',color:'black' }}>
          <div className="card-header">
            your due bills
          </div>
          <div className="card-body text-center">
            <h5 className="card-title">Name : {bill.name}</h5>
            <h6>Bill Number : {bill.billNo}</h6>
            <p>Pay your bills within 15 days after generating </p>
            <p>Amount : {bill.amount}</p>
            <p>date : {bill.date}</p>
            <h5 className='text-danger'> status : pending</h5>

          </div>
          <div className="card-footer ">
           These bills are generated by Admin

           <div className="text-end">
           <button onClick={()=>payBill(bill)} className="btn btn-primary me-md-2" type="button" >Pay</button>

            </div>
         
          </div>
        </div>
      </div>

    </div>
  )
}

export default ViewBills